#!/usr/bin/env bash

##########################################################################################################################
## SCRIPT TO CALCULATE DUAL-REGRESSION-BASED RESTING-STATE FUNCTIONAL CONNECTIVITY
##
## This script can be run on its own, by filling in the appropriate parameters
## Alternatively this script gets called from batch_process.sh, where you can use it to run N sites, one after the other.
##
## Make sure you have installed FSL with an version >= 4.1.5.
##
## Written by Xi-Nian Zuo, Maarten Mennes & Michael Milham
## for more information see www.nitrc.org/projects/fcon_1000
##
##########################################################################################################################


## analysisdirectory
dir=$1
## full/path/to/subject_list.txt containing subjects you want to run
subject_list=$2
## image to extract timeseries from. default = rest_res2standard.nii.gz
postprocessing_mni_image=$3
## file containing DR templates with full/path/to/DR_template.nii.gz
## default = metaICA.nii.gz this map is included in the templates folder
DR_template=$4
## image with full/path/to/group-mask. default is the mni mask 
mask=$5

## directory setup
## see below


##########################################################################################################################
##---START OF SCRIPT----------------------------------------------------------------------------------------------------##
##########################################################################################################################

echo ---------------------------------------
echo !!!! RUNNING DUAL REGRESSION !!!!
echo ---------------------------------------


## Get subjects to run
subjects=$( cat ${subject_list} )

## A. SUBJECT LOOP
for subject in $subjects
do

## directory setup
func_dir=${dir}/${subject}/func
## DR-derived RSFC maps
DR_dir=${dir}/${subject}/func/DR


echo --------------------------
echo running subject ${subject}
echo --------------------------

mkdir -p ${DR_dir} ; cd ${DR_dir}

## COMPONENT LOOP ; Loop through 20 components
for (( coll=1 ; coll <= 20 ; coll++ )) 
do

echo RUNNING COMPONENT ${coll}

## 1. Do First Regression using univariate linear regression model; not normalized
## 1a. get DR template for specific component
let k=${coll}-1
fslroi ${DR_template} dr_template.nii.gz ${k} 1
## 1b. do first regression
echo "First regression: DR_template map as regressor ..."
fsl_glm -i ${func_dir}/${postprocessing_mni_image} -d dr_template.nii.gz -o dr_tc.1D --demean -m ${mask}

## 2. Do Second Regression: using univariate linear regression model; not normalized
## this regression uses the individual time course output generated by the first regression
echo "Second regression: individual time course as regressor ..."
fsl_glm -i ${func_dir}/${postprocessing_mni_image} -d dr_tc.1D -o dr_ic${coll}.nii.gz --out_z=dr_ic${coll}_Z_2standard --out_sigsq=dr_ic${coll}_sigsq --demean -m ${mask}
## only keep the first volume of the output image
fslroi dr_ic${coll}_Z_2standard.nii.gz dr_ic${coll}_Z_2standard.nii.gz 0 1

## END OF COMPONENT LOOP
done

## END OF SUBJECT LOOP
done
